name: mediagui
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - numba
  - llvmlite
  - matplotlib
  - pyqt6
  - pyinstaller
  - pip
  - pip:
      - altgraph
      - contourpy
      - cycler
      - fonttools
      - kiwisolver
      - matplotlib
      - opencv-python
      - opencv-python-headless
      - packaging
      - pillow
      - pyinstaller-hooks-contrib
      - pyparsing
      - pyqt6
      - pyqt6-qt6
      - pyqt6-sip
      - python-dateutil
      - six