package:
  name: mediagui
  version: "1.0.0"

source:
  path: .

requirements:
  host:
    - python
    - setuptools
  run:
    - python>=3.8
    - pyqt6
    - opencv
    - numpy

app:
  entry: python -m mediagui
  
about:
  home: https://github.com/khicken/mediaGUI
  license: MIT
  summary: 'Cross-platform tool (GUI) to concatenate and speed up video(s)'